# Generated by Django 2.2 on 2019-05-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mnist', '0002_auto_20190513_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='training_record_mnist',
        ),
    ]
