# Generated by Django 2.2 on 2019-05-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mnist', '0003_delete_training_record_mnist'),
    ]

    operations = [
        migrations.CreateModel(
            name='training_record_mnist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_mnist', models.CharField(default='No record', max_length=2048)),
            ],
        ),
    ]
