# Generated by Django 2.2 on 2019-05-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nnbasedclassifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_record',
            name='record_cifar',
            field=models.CharField(default='No record', max_length=2048),
        ),
    ]
