# Generated by Django 2.2 on 2019-05-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nnbasedclassifier', '0003_auto_20190513_0848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='training_record_cifar',
        ),
        migrations.DeleteModel(
            name='training_record_mnist',
        ),
    ]
